### ISSUE TITLE
Don't vendor vedis, compile against

### ISSUE THREAD

**Issue by zzak** [matsumoto-r/mruby-vedis#6]
I think we should statically compile this dependency, similar to matsumoto-r/mruby-redis#31.

Currently, vedis is vendored [in src](https://github.com/matsumoto-r/mruby-vedis/blob/master/src/vedis.c).

I can help with this after I finish hiredis support for mruby-redis. :heart_eyes:

**Comment by matsumoto-r** [comment]
Wow!! Thank you for your propose. I also think we should statically compile it.
